name = "ReactiveDynamics"
uuid = "c7456e7d-545a-4b79-91ea-6e93d96dd4d4"
version = "0.2.7"

[deps]
ACSets = "227ef7b5-1206-438b-ac65-934d6da304b8"
AlgebraicAgents = "f6eb0ae3-10fa-40e6-88dd-9006ba45093a"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeneratedExpressions = "84d730a5-1eb9-4187-a799-27dd07f33a14"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ACSets = "0.2.6"
CSV = "0.10"
ComponentArrays = "0.14"
Crayons = "4.1"
DataFrames = "1.6"
Distributions = "0.25"
GeneratedExpressions = "0.1"
IJulia = "1.24"
JLD2 = "0.4"
JSON = "0.21"
MacroTools = "0.5"
Plots = "1.39"
Pluto = "0.19"
PlutoUI = "0.7"
Reexport = "1.2"
SafeTestsets = "0.1"
Statistics = "1.9"
StatsFuns = "1.3"
Symbolics = "5.5"
TOML = "1.0"
Tables = "1.10"
julia = "1.9"
